{"name": "test_negative_auth_check[no_token]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/logs/log_2023-01-08_15-37-17.log'", "trace": "self = <tests.test_user_auth.TestUserAuth object at 0x109209400>\n\n    def setup(self):\n    \n        data = {\n            'email': 'vinkotov@example.com',\n            'password': '1234'\n        }\n    \n>       response1 = MyRequests.post(\"/user/login\", data=data)\n\ntests/test_user_auth.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlib/my_requests.py:17: in post\n    return MyRequests._send(url, data, headers, cookies, 'POST')\nlib/my_requests.py:39: in _send\n    Logger.add_request(url, data, headers, cookies, method)\nlib/logger.py:28: in add_request\n    cls._write_log_to_file(data_to_add)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'lib.logger.Logger'>\ndata = \"\\n-----\\nTest: tests/test_user_auth.py::TestUserAuth::test_negative_auth_check[no_token] (setup)\\nDate: 2023-01-08 15...gin\\nRequest data: {'email': 'vinkotov@example.com', 'password': '1234'}\\nRequest headers: {}\\nRequest cookies: {}\\n\\n\"\n\n    @classmethod\n    def _write_log_to_file(cls, data: str):\n>       with open(cls.file_name, 'a', encoding='utf-8') as logger_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/logs/log_2023-01-08_15-37-17.log'\n\nlib/logger.py:12: FileNotFoundError"}, "description": "This test checks authorization code w/o sending auth cookie or token", "parameters": [{"name": "condition", "value": "'no_token'"}], "start": 1673177837862, "stop": 1673177837862, "uuid": "ec34a1c1-9d1e-4270-b466-fd379fb3917f", "historyId": "2efb9a119acc01d480f794af7e24ee19", "testCaseId": "4551f7b5d13db64c4fa185c3def4491f", "fullName": "tests.test_user_auth.TestUserAuth#test_negative_auth_check", "labels": [{"name": "epic", "value": "Authorization cases"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "MacBook-Pro-Elizaveta.local"}, {"name": "thread", "value": "54522-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}]}